kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["applicationconnector.kyma-project.io"]
    resources: ["applications"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources: ["serviceinstances"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["security.istio.io"]
    resources: ["authorizationpolicies"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Values.global.namespace }}:{{ .Chart.Name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
