# Migrate app-connector-certs for cacert value
# This script is meant to fix problem with api empty gateway cert that remains after migration to from Kyma 1.16 to Kyma 1.17
#
#  Compass Runtime Agent while establishing SKR connection with management plane fills certificate for API gateway by
#  setting cacert filed in secret
#
#  In 1.16 secret name is kyma-gatewy-certs-cacert
#  W 1.17 secret name is app-connector-certs
#
# During upgrade:
#  1. New secret is created app-connector-certs the old one kyma-gatewy-certs-cacert is going to dissapear
#  2. Helm updates deployment of Compass Runtime Agent, and new secret is set as APP_CA_CERTIFICATES_SECRET kyma-gatewy-certs-cacert -> app-connector-certs
#
#  Secret app-connector-certs has initially empty field cacert.
#  So during upgrade in our job we should pass cacert value from old secret kyma-gatewy-certs-cacert into new secret app-connector-certs
#
#  Currently is will be populated only after new connection with Compass is established

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name | lower | replace " " "-" }}-cacert-migrate-job
  namespace: istio-system
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name | lower | replace " " "-" }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name | lower | replace " " "-" }}-cacert-migrate-job
      namespace: {{ .Values.global.namespace }}
      annotations:
        sidecar.istio.io/inject: “false”
      labels:
        release: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name | lower | replace " " "-" }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: {{ template "name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name | lower | replace " " "-" }}-cacert-migrate
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name | lower | replace " " "-"}}-cacert-migrate-job
          image:  eu.gcr.io/kyma-project/incubator/develop/k8s-tools:20201023-5de446cf
          env:
            - name: OLD_SECRET_NAME
              value: {{ .Values.cacert_migrate_setup_job.secrets.oldConnectorGatewaySecret.name }}
            - name: OLD_SECRET_NAMESPACE
              value: {{ .Values.cacert_migrate_setup_job.secrets.oldConnectorGatewaySecret.namespace }}
            - name: NEW_SECRET_NAME
              value: {{ .Values.cacert_migrate_setup_job.secrets.newConnectorGatewaySecret.name }}
            - name: NEW_SECRET_NAMESPACE
              value: {{ .Values.cacert_migrate_setup_job.secrets.newConnectorGatewaySecret.namespace }}
          command:
            - bash
            - -c
            - |
{{ tpl (.Files.Get "files/cacert-migrate.sh" | printf "%s" | indent 14) . }}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name | lower |replace " " "-"}}-cacert-migrate
  namespace:  istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name | lower | replace " " "-"}}-cacert-migrate
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "patch"]
    resourceNames:
      - {{ .Values.cacert_migrate_setup_job.secrets.oldConnectorGatewaySecret.name }}
      - {{ .Values.cacert_migrate_setup_job.secrets.newConnectorGatewaySecret.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name | lower | replace " " "-"}}-cacert-migrate
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name | lower | replace " " "-"}}-cacert-migrate
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name | lower | replace " " "-"}}-cacert-migrate
    namespace: istio-system


